name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./winvice-nightly && dotnet tool restore && dotnet cake build.cake 

      - run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - run: choco install --prerelease -s ./winvice-nightly winvice-nightly
      - run: Get-Command x64sc
      - run: choco apikey --key ${{ secrets.CHOCO_KEY }} --source https://push.chocolatey.org/
      - run: choco push $(Get-ChildItem winvice-nightly/bin/Debug/winvice-nightly*.nupkg).FullName --source https://push.chocolatey.org/
