name: VICE Build
on:
  workflow_dispatch:
  push:
    paths:
      - 'winvice-nightly/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./winvice-nightly && dotnet tool restore && dotnet cake build.cake 

      - run: choco install --prerelease -s ./winvice-nightly winvice-nightly
      - run: Get-Command x64sc
      - run: choco push --api-key ${{ secrets.CHOCO_KEY }} $(Get-ChildItem winvice-nightly/winvice-nightly*.nupkg).FullName --source https://push.chocolatey.org/
        if: always()
